//! The std-runtime start glue — the analogue of `std`'s `lang_start`.
//!
//! The process entry point `_start` lives in the separate `purert` runtime crate
//! (crt0's job, not std's). After it decodes `argc`/`argv`/`envp` it calls
//! `__purestd_start` here, which initializes the environment, runs the user
//! `main` (exported as `__purestd_main` by [`crate::entry!`]), and exits.
//!
//! Gated behind the `rt` feature: like `std`, `purestd` provides this by
//! default, but a host runtime may supply its own and turn it off.

use crate::{env, syscall};

extern "C" {
    /// The user program's entry, generated by [`crate::entry!`].
    fn __purestd_main() -> i32;
}

/// Called by the `purert` `_start` with the decoded argument/environment
/// vectors. Runs `main` and exits; never returns.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn __purestd_start(
    argc: usize,
    argv: *const *const u8,
    envp: *const *const u8,
) -> ! {
    env::init(argc, argv, envp);
    let code = __purestd_main();
    syscall::exit_group(code)
}
