//! Kernel/loader process entry. Gated behind `rt`; a host runtime may provide
//! its own `_start` and call `__purestd_main` itself.
//!
//! The argument-passing ABI differs by platform:
//!
//! * **macOS/arm64** uses the Mach-O `LC_MAIN` convention: the loader calls the
//!   entry like `main(argc, argv, envp, apple)` with the values already in
//!   `x0..x3`. So `_start` is a plain `extern "C"` function — no naked prologue.
//! * **Linux** passes them on the initial stack (`sp -> argc, argv.., envp..`).
//!   The naked `_start` lives in [`crate::arch`] (the asm differs per arch);
//!   it captures `sp` and tail-calls [`rust_start`] here.

use crate::{env, syscall};

extern "C" {
    /// The user program's entry, generated by [`crate::entry!`].
    fn __purestd_main() -> i32;
}

/// macOS/arm64 entry — arguments arrive in registers.
#[cfg(all(target_os = "macos", target_arch = "aarch64"))]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn _start(
    argc: usize,
    argv: *const *const u8,
    envp: *const *const u8,
) -> ! {
    env::init(argc, argv, envp);
    let code = __purestd_main();
    syscall::exit_group(code)
}

/// Linux entry — `stack` points at `argc`, the classic SysV initial stack.
/// Called by the naked `_start` in [`crate::arch`].
#[cfg(target_os = "linux")]
pub(crate) unsafe extern "C" fn rust_start(stack: *const usize) -> ! {
    let argc = *stack;
    let argv = stack.add(1) as *const *const u8;
    // envp follows argv and its NULL terminator: argv[argc] is NULL, then envp.
    let envp = argv.add(argc + 1);
    env::init(argc, argv, envp);
    let code = __purestd_main();
    syscall::exit_group(code)
}
